main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("create/", views.URLCreateView, name="create"),
    path("url/<name>/", views.URLDetailView, name="url"),
    path("list/<page>", views.URLListView.as_view(), name="list")
]

shlink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Set DEBUG = False for Error pages

handler404 = views.handler404
handler505 = views.handler500

   

main/models.py
from django.db import models
from django.core import validators

# Create your models here.
class ShortenedURL(models.Model):
    name = models.SlugField(validators=[validators.MinLengthValidator(2)], unique=True)
    url = models.URLField(validators=[validators.URLValidator()])

    def __str__(self):
        return f"{self.name} ({self.url})"

main/forms.py
from django import forms
from django.core import validators
from . import models


class URLForm(forms.ModelForm):
    name = forms.SlugField(validators=[validators.MinLengthValidator(2)], widget=forms.TextInput(
        attrs={
            "class": "form-control",
            "placeholder": "Name"
        }
    ))

    url = forms.URLField(validators=[validators.URLValidator], widget=forms.URLInput(
        attrs={
            "class": "form-control",
            "placeholder": "URL"
        }
    ))

    def clean_name(self):
        data = self.cleaned_data["name"]
        if not data.islower():
            raise forms.ValidationError("Shortened URL names should be in lowercase.")
        return data

    class Meta:
        model = models.ShortenedURL
        fields = "__all__"

main/views.py
from django.http import Http404
from django.shortcuts import render
from django.views import generic
from django.template.defaultfilters import slugify
from django.contrib import messages
from django.urls import reverse
from . import models
from . import forms


# Create your views here.
class HomeView(generic.TemplateView):
    template_name = "home.html"


class URLListView(generic.ListView):
    model = models.ShortenedURL
    template_name = "list.html"
    context_object_name = "urlList"

    def get_context_data(self, **kwargs):
        if int(self.kwargs["page"]) <= 0:
            raise Http404()

        context = super().get_context_data(**kwargs)
        urlList = models.ShortenedURL.objects.order_by()[(int(self.kwargs["page"]) * 5 - 5):(int(self.kwargs["page"]) * 5)]
        context[self.context_object_name] = urlList
        context["amount"] = len(urlList)

        if len(urlList) == 0:
            raise Http404()

        context["page"] = self.kwargs["page"]
        return context


def URLCreateView(request):
    form = None

    if request.method == "GET":
        form = forms.URLForm()
    elif request.method == "POST":
        form = forms.URLForm(request.POST)

        if form.is_valid():
            form_data = form.cleaned_data
            urlName = form_data.get("name")
            form.name = urlName
            form.save()

            messages.success(
                request,
                f"You have just created a shortened URL, which is {request.get_host()}{reverse('main:url', kwargs={'name': form.name}).replace(form.name.lower(), form.name)}"
            )

    return render(request, "create.html", context={
        "form": form
    })


def URLDetailView(request, name):
    return render(request, "url.html", context={
        "url": models.ShortenedURL.objects.get(name=name)
    })


def handler404(request, exception):
    return render(request, "err.html", status=404)


def handler500(request):
    return render(request, "err.html", status=500)

main/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--- Quicksand (Google Fonts) --->
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet">
        <!--- Bootstrap 4 --->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <!--- Static Files --->
        <link rel="icon" href="{% static 'img/linkDark.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

        <title>{% block title %}Base{% endblock %}</title>
    </head>
    <body class="bg-light">
        <nav class="navbar navbar-expand-sm navbar-dark flex-column flex-sm-row" style="background-color: rgb(35, 35, 35);">
            <a class="navbar-brand" href="{% url "main:home" %}">
                <img src="{% static "img/linkLight.png" %}" alt="link">
                shlink
            </a>
            <ul class="navbar-nav">
                <li class="nav-item navbar-left {% block navhome %}{% endblock %}">
                    <a class="nav-link" href="{% url "main:home" %}">Home</a>
                </li>
                <li class="nav-item navbar-left {% block navcreate %}{% endblock %}">
                    <a class="nav-link" href="{% url "main:create" %}">Create Link</a>
                </li>
            </ul>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

main/templates/create.html
<!DOCTYPE html>

{% extends "base.html" %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}shlink - Create{% endblock %}
    </head>
    <body>
        {% block navcreate %}active{% endblock %}

        {% block body %}
            <div class="jumbotron fluid-jumbotron bg-light text-black" style="height: 100vh; width: 100vw;">
                <form action="{% url "main:create" %}" method="POST">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="{{ form.url.id_for_label }}">Link</label>
                        {{ form.url }}
                        <span class="text-danger form-text">{{ form.url.errors.0 }}</span>
                    </div>

                    <div class="form-group">
                        <label for="{{ form.name.id_for_label }}">Shortened Name</label>
                        {{ form.name }}
                        <span class="text-danger form-text">{{ form.name.errors.0 }}</span>
                    </div>

                    <input class="btn btn-outline-dark btn-md"  type="submit">
                </form>

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success" style="margin-top: 2.5%;">
                            <h4 class="alert-heading">You have made the shortened <a class="alert-link" href="{% url "main:url" name=form.name.value %}">URL</a>!</h4>
                            <button type="button" class="close" aria-label="Close" onclick="document.querySelector('div.alert.alert-success').remove()">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p>You and your friends may use it, to get to the original URL.</p>
                            <hr>
                            <p class="mb-0">
                                Your shortened <a class="alert-link" href="{% url "main:url" name=form.name.value %}">URL</a>
                                is linked to <a class="alert-link" href="{{ form.url.value }}">{{ form.url.value }}</a>.
                            </p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        {% endblock %}
    </body>
</html>

main/templates/err.html
<!DOCTYPE html>

{% extends "base.html" %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}shlink - Error{% endblock %}
    </head>
    <body>
        {% block body %}
            <div class="jumbotron fluid-jumbotron bg-light">
                <h1 class="display-1 text-center mx-auto">An Error Has Happened.</h1>
                <p class="lead text-center mx-auto">Go back to <a class="text-muted" href="{% url "main:home" %}">home</a>?</p>
            </div>
        {% endblock %}
    </body>
</html>

main/templates/home.html
<!DOCTYPE html>

{% extends "base.html" %}
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}shlink - Home{% endblock %}
    </head>
    <body>
        {% block navhome %}active{% endblock %}

        {% block body %}
            <div class="jumbotron fluid-jumbotron" style="height: 100vh; width: 100vw; background-color: rgb(30, 30, 30);">
                <h1 class="display-1 text-center text-light">shlink</h1>
                <p class="lead text-center text-light">
                    The solution all your URL shrinking needs.
                    <br>
                    List of links made <a href="{% url "main:list" page=1 %}">here</a>.
                </p>
            </div>
        {% endblock %}
    </body>
</html>

main/templates/list.html
<!DOCTYPE html>

{% extends "base.html" %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}shlink - URL List{% endblock %}
    </head>
    <body>
        {% block body %}
            <div class="jumbotron bg-light" style="overflow: none; height: 100vh; width: 100vw;">
                <label for="searchbar">Search</label>
                <input type="text" name="searchbar" class="form-control">
                <br>
                {% for url in urlList %}
                    <div class="card d-block p-2">
                        <div class="card-body">
                            <h5 class="card-title">{{ url.name }}</h5>
                            <p class="card-text"><a href="{% url "main:url" name=url.name %}">{{ url.url }}</a></p>
                        </div>
                    </div>
                {% endfor %}
                <script>
                    let searchBar = document.querySelector("input")
                    let entries = document.querySelectorAll("div.card")

                    searchBar.addEventListener("input", () => {
                        entries.forEach((card) => {
                            let header = card.querySelector("div.card-body h5.card-title")
                            console.log(header.textContent, searchBar.value)
                            if (header.textContent.includes(searchBar.value)) {
                                card.classList.add("d-block")
                                card.style.display = "inline"
                            } else {
                                card.classList.remove("d-block")
                                card.style.display = "none"
                            }
                        })
                    })
                </script>
                <br><br><br>
                <ul class="pagination justify-content-center">
                    {% if page|add:0 != 1 %}
                        <li class="page-item"><a class="page-link" href="{% url "main:list" page=page|add:-1 %}">&laquo;</a></li>
                    {% endif %}
                    <li class="page-item active"><a class="page-link" href="{% url "main:list" page=page %}">{{ page }}</a></li>
                    {% if amount|add:0 == 5 %}
                        <li class="page-item"><a class="page-link" href="{% url "main:list" page=page|add:1 %}">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endblock %}
    </body>
</html>

main/templates/url.html
<!DOCTYPE html>

{% extends "base.html" %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% block title %}shlink - Redirecting to {{ url.url }}{% endblock %}
    </head>
    <body>
        {% block body %}
            <div class="jumbotron fluid-jumbotron bg-light">
                <div class="loader"></div>
                <p></p><p></p>
                <br>
                <br>
                <h1 class="display-3 mx-auto text-center"> Redirecting to {{ url.url }}</h1>
                <p class="display-4 lead mx-auto text-center">in 5 seconds</p>
            </div>
            <script>
                let numOfSeconds = 5

                setInterval(() => {
                    numOfSeconds--

                    document.querySelector("p.display-4.lead.mx-auto.text-center").textContent = `in ${numOfSeconds} seconds`
                }, 1000)

                setTimeout(() => {
                    location.replace("{{ url.url }}")
                }, 5000)
            </script>
        {% endblock %}
    </body>
</html>